import type {
  User,
  Gift,
  RecurringGift,
  Course,
  CourseModule,
  UserCourseProgress,
  CourseNote,
  FoundationGrant,
  CommunicationPreferences,
  ContentItem,
  PortalEvent,
  CommunicationTemplate,
  ActivityEvent,
  UserRoleAssignment,
  UserQuizAttempt,
  CourseModuleEvent,
  CourseCohort,
  CourseCohortMember,
  CourseDiscussionThread,
  CourseDiscussionReply,
} from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'admin-001',
    email: 'admin@favor.local',
    firstName: 'Avery',
    lastName: 'Admin',
    constituentType: 'individual',
    lifetimeGivingTotal: 0,
    rddAssignment: 'Internal',
    createdAt: '2024-01-10T14:00:00Z',
    lastLogin: '2026-02-03T12:30:00Z',
    isAdmin: true,
  },
  {
    id: 'user-001',
    email: 'emma@favor.local',
    firstName: 'Emma',
    lastName: 'Carter',
    constituentType: 'individual',
    lifetimeGivingTotal: 840,
    rddAssignment: 'Southeast - Rachel M.',
    createdAt: '2024-05-22T14:00:00Z',
    lastLogin: '2026-02-02T15:12:00Z',
  },
  {
    id: 'user-002',
    email: 'daniel@favor.local',
    firstName: 'Daniel',
    lastName: 'Ross',
    constituentType: 'major_donor',
    lifetimeGivingTotal: 12850,
    rddAssignment: 'Central - Jordan K.',
    createdAt: '2022-03-18T09:00:00Z',
    lastLogin: '2026-02-01T10:25:00Z',
  },
  {
    id: 'user-003',
    email: 'pastor@favor.local',
    firstName: 'Lydia',
    lastName: 'Hughes',
    constituentType: 'church',
    lifetimeGivingTotal: 5650,
    rddAssignment: 'Midwest - Olivia S.',
    createdAt: '2021-07-03T10:00:00Z',
    lastLogin: '2026-02-01T09:44:00Z',
  },
  {
    id: 'user-004',
    email: 'foundation@favor.local',
    firstName: 'Priya',
    lastName: 'Desai',
    constituentType: 'foundation',
    lifetimeGivingTotal: 45200,
    rddAssignment: 'Foundations - Marcus L.',
    createdAt: '2020-02-14T08:00:00Z',
    lastLogin: '2026-01-29T11:15:00Z',
  },
  {
    id: 'user-005',
    email: 'daf@favor.local',
    firstName: 'Miguel',
    lastName: 'Ortiz',
    constituentType: 'daf',
    lifetimeGivingTotal: 21400,
    rddAssignment: 'West - Hannah G.',
    createdAt: '2023-10-01T16:00:00Z',
    lastLogin: '2026-02-03T08:45:00Z',
  },
  {
    id: 'user-006',
    email: 'ambassador@favor.local',
    firstName: 'Chloe',
    lastName: 'Nguyen',
    constituentType: 'ambassador',
    lifetimeGivingTotal: 9200,
    rddAssignment: 'Northeast - Isaiah P.',
    createdAt: '2023-04-12T13:30:00Z',
    lastLogin: '2026-02-02T18:20:00Z',
  },
  {
    id: 'user-007',
    email: 'volunteer@favor.local',
    firstName: 'Isaac',
    lastName: 'Rivera',
    constituentType: 'volunteer',
    lifetimeGivingTotal: 200,
    rddAssignment: 'Volunteer Ops - Kayla R.',
    createdAt: '2025-06-19T10:00:00Z',
    lastLogin: '2026-02-02T17:40:00Z',
  },
];

export const MOCK_GIFTS: Gift[] = [
  {
    id: 'gift-001',
    userId: 'user-001',
    amount: 100,
    date: '2026-01-12',
    designation: 'Clean Water Initiative',
    isRecurring: true,
    receiptSent: true,
    source: 'imported',
  },
  {
    id: 'gift-002',
    userId: 'user-001',
    amount: 250,
    date: '2025-11-18',
    designation: 'Where Most Needed',
    isRecurring: false,
    receiptSent: true,
    source: 'imported',
  },
  {
    id: 'gift-003',
    userId: 'user-002',
    amount: 5000,
    date: '2025-12-05',
    designation: 'Leadership Development',
    isRecurring: false,
    receiptSent: true,
    source: 'imported',
  },
  {
    id: 'gift-004',
    userId: 'user-003',
    amount: 1200,
    date: '2026-01-30',
    designation: 'Church Missions Fund',
    isRecurring: false,
    receiptSent: true,
    source: 'imported',
  },
  {
    id: 'gift-005',
    userId: 'user-004',
    amount: 15000,
    date: '2025-10-10',
    designation: 'Foundation Grant - Education',
    isRecurring: false,
    receiptSent: true,
    source: 'imported',
  },
  {
    id: 'gift-006',
    userId: 'user-005',
    amount: 2500,
    date: '2026-01-08',
    designation: 'DAF Grant - Community Health',
    isRecurring: false,
    receiptSent: true,
    source: 'imported',
  },
  {
    id: 'gift-007',
    userId: 'user-006',
    amount: 800,
    date: '2025-12-22',
    designation: 'Ambassador Campaign',
    isRecurring: false,
    receiptSent: true,
    source: 'imported',
  },
];

export const MOCK_RECURRING_GIFTS: RecurringGift[] = [
  {
    id: 'recurring-001',
    userId: 'user-001',
    amount: 100,
    frequency: 'monthly',
    nextChargeDate: '2026-02-15',
    stripeSubscriptionId: 'sub_mock_001',
    status: 'active',
    createdAt: '2024-08-01T12:00:00Z',
  },
  {
    id: 'recurring-002',
    userId: 'user-003',
    amount: 500,
    frequency: 'monthly',
    nextChargeDate: '2026-02-10',
    stripeSubscriptionId: 'sub_mock_002',
    status: 'active',
    createdAt: '2023-03-01T12:00:00Z',
  },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'course-africa',
    title: 'Africa Programs Overview',
    description: 'A guided tour of Favor International\'s four core program areas across Africa.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1489493173507-55f0239eaf16?q=80&w=1200&auto=format&fit=crop',
    accessLevel: 'partner',
    sortOrder: 1,
    createdAt: '2025-10-01T12:00:00Z',
    moduleCount: 5,
    status: 'published',
    isLocked: false,
    isPaid: false,
    enforceSequential: true,
  },
  {
    id: 'course-vision',
    title: 'Vision and the Great Commission',
    description: 'Carol Ward teaching on Favor\'s vision, indigenous leadership, and disciple-making.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&auto=format&fit=crop',
    accessLevel: 'partner',
    sortOrder: 2,
    createdAt: '2025-11-05T12:00:00Z',
    moduleCount: 5,
    status: 'published',
    isLocked: false,
    isPaid: false,
    enforceSequential: true,
  },
  {
    id: 'course-us',
    title: 'Favor US Introduction',
    description: 'Meet the US team and learn how Favor is expanding domestic partnerships.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1200&auto=format&fit=crop',
    accessLevel: 'partner',
    sortOrder: 3,
    createdAt: '2025-12-01T12:00:00Z',
    moduleCount: 5,
    status: 'published',
    isLocked: false,
    isPaid: false,
    enforceSequential: true,
  },
  {
    id: 'course-foundation',
    title: 'Foundation Impact Briefings',
    description: 'Board-ready insights and grant outcomes for foundation partners.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1200&auto=format&fit=crop',
    accessLevel: 'foundation',
    sortOrder: 4,
    createdAt: '2026-01-03T12:00:00Z',
    moduleCount: 4,
    status: 'published',
    isLocked: true,
    isPaid: false,
    enforceSequential: true,
  },
  {
    id: 'course-ambassador',
    title: 'Ambassador Training Intensive',
    description: 'Tools, messaging, and playbooks for advocacy and fundraising.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515165562835-c4c8b291f5f0?q=80&w=1200&auto=format&fit=crop',
    accessLevel: 'ambassador',
    sortOrder: 5,
    createdAt: '2026-01-10T12:00:00Z',
    moduleCount: 6,
    status: 'published',
    isLocked: true,
    isPaid: false,
    enforceSequential: true,
  },
  {
    id: 'course-major',
    title: 'Major Donor Briefing: 2025 Financials',
    description: 'Deep-dive on financial stewardship and strategic initiatives.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?q=80&w=1200&auto=format&fit=crop',
    accessLevel: 'major_donor',
    sortOrder: 6,
    createdAt: '2026-01-15T12:00:00Z',
    moduleCount: 3,
    status: 'draft',
    isLocked: true,
    isPaid: false,
    enforceSequential: true,
  },
];

export const MOCK_COURSE_MODULES: CourseModule[] = [
  {
    id: 'course-africa-module-1',
    courseId: 'course-africa',
    title: 'Program Overview and Context',
    description: 'Orientation to Favor\'s model and regional focus.',
    cloudflareVideoId: 'demo-africa-1',
    sortOrder: 1,
    durationSeconds: 920,
  },
  {
    id: 'course-africa-module-2',
    courseId: 'course-africa',
    title: 'Education & Discipleship',
    description: 'How local schools and mentors shape long-term impact.',
    cloudflareVideoId: 'demo-africa-2',
    sortOrder: 2,
    durationSeconds: 860,
  },
  {
    id: 'course-africa-module-3',
    courseId: 'course-africa',
    title: 'Healthcare & Community Health',
    description: 'Clinics, maternal health, and community resilience.',
    cloudflareVideoId: 'demo-africa-3',
    sortOrder: 3,
    durationSeconds: 780,
  },
  {
    id: 'course-africa-module-4',
    courseId: 'course-africa',
    title: 'Economic Empowerment',
    description: 'Microfinance and entrepreneurship initiatives.',
    cloudflareVideoId: 'demo-africa-4',
    sortOrder: 4,
    durationSeconds: 720,
  },
  {
    id: 'course-africa-module-5',
    courseId: 'course-africa',
    title: 'Stories from the Field',
    description: 'Testimonies and partner highlights.',
    cloudflareVideoId: 'demo-africa-5',
    sortOrder: 5,
    durationSeconds: 660,
  },
  {
    id: 'course-vision-module-1',
    courseId: 'course-vision',
    title: 'Favor Vision and Values',
    description: 'Timeless values guiding the ministry.',
    cloudflareVideoId: 'demo-vision-1',
    sortOrder: 1,
    durationSeconds: 840,
  },
  {
    id: 'course-vision-module-2',
    courseId: 'course-vision',
    title: 'Indigenous Leadership Model',
    description: 'Empowering local leaders for sustainable change.',
    cloudflareVideoId: 'demo-vision-2',
    sortOrder: 2,
    durationSeconds: 900,
  },
  {
    id: 'course-vision-module-3',
    courseId: 'course-vision',
    title: 'Discipleship Pathway',
    description: 'A practical look at Favor\'s discipleship rhythm.',
    cloudflareVideoId: 'demo-vision-3',
    sortOrder: 3,
    durationSeconds: 780,
    type: 'reading',
    resourceUrl: '/mock/discipleship-pathway.pdf',
  },
  {
    id: 'course-vision-module-4',
    courseId: 'course-vision',
    title: 'Mobilizing the Church',
    description: 'Engaging churches and pastors globally.',
    cloudflareVideoId: 'demo-vision-4',
    sortOrder: 4,
    durationSeconds: 740,
  },
  {
    id: 'course-vision-module-5',
    courseId: 'course-vision',
    title: 'Partnership in Action',
    description: 'Stories of partners shaping the mission.',
    cloudflareVideoId: 'demo-vision-5',
    sortOrder: 5,
    durationSeconds: 710,
  },
  {
    id: 'course-us-module-1',
    courseId: 'course-us',
    title: 'Welcome to Favor US',
    description: 'US team overview and vision.',
    cloudflareVideoId: 'demo-us-1',
    sortOrder: 1,
    durationSeconds: 720,
  },
  {
    id: 'course-us-module-2',
    courseId: 'course-us',
    title: 'Trauma Healing in Schools',
    description: 'Upcoming initiatives in US communities.',
    cloudflareVideoId: 'demo-us-2',
    sortOrder: 2,
    durationSeconds: 760,
    type: 'video',
  },
  {
    id: 'course-us-module-3',
    courseId: 'course-us',
    title: 'Ambassador Opportunities',
    description: 'Ways to lead and advocate locally.',
    cloudflareVideoId: 'demo-us-3',
    sortOrder: 3,
    durationSeconds: 680,
  },
  {
    id: 'course-us-module-4',
    courseId: 'course-us',
    title: 'Volunteer Journey',
    description: 'What to expect in the volunteer pathway.',
    cloudflareVideoId: 'demo-us-4',
    sortOrder: 4,
    durationSeconds: 640,
  },
  {
    id: 'course-us-module-5',
    courseId: 'course-us',
    title: 'Next Steps',
    description: 'Resources and next actions for partners.',
    cloudflareVideoId: 'demo-us-5',
    sortOrder: 5,
    durationSeconds: 620,
  },
  {
    id: 'course-foundation-module-1',
    courseId: 'course-foundation',
    title: 'Grant Lifecycle Overview',
    description: 'How Favor manages grants end-to-end.',
    cloudflareVideoId: 'demo-foundation-1',
    sortOrder: 1,
    durationSeconds: 780,
  },
  {
    id: 'course-foundation-module-2',
    courseId: 'course-foundation',
    title: 'Impact Measurement',
    description: 'Reporting outcomes and KPIs.',
    cloudflareVideoId: 'demo-foundation-2',
    sortOrder: 2,
    durationSeconds: 860,
  },
  {
    id: 'course-foundation-module-3',
    courseId: 'course-foundation',
    title: 'Financial Stewardship',
    description: 'Budgeting and accountability practices.',
    cloudflareVideoId: 'demo-foundation-3',
    sortOrder: 3,
    durationSeconds: 720,
  },
  {
    id: 'course-foundation-module-4',
    courseId: 'course-foundation',
    title: 'Board Briefings',
    description: 'Preparing leadership-ready updates.',
    cloudflareVideoId: 'demo-foundation-4',
    sortOrder: 4,
    durationSeconds: 680,
  },
  {
    id: 'course-ambassador-module-1',
    courseId: 'course-ambassador',
    title: 'Ambassador DNA',
    description: 'Core expectations and community impact.',
    cloudflareVideoId: 'demo-amb-1',
    sortOrder: 1,
    durationSeconds: 760,
  },
  {
    id: 'course-ambassador-module-2',
    courseId: 'course-ambassador',
    title: 'Storytelling Framework',
    description: 'How to share the mission clearly.',
    cloudflareVideoId: 'demo-amb-2',
    sortOrder: 2,
    durationSeconds: 820,
    type: 'quiz',
    resourceUrl: '/mock/ambassador-quiz.pdf',
  },
  {
    id: 'course-ambassador-module-3',
    courseId: 'course-ambassador',
    title: 'Event Hosting Playbook',
    description: 'Planning and executing events.',
    cloudflareVideoId: 'demo-amb-3',
    sortOrder: 3,
    durationSeconds: 780,
  },
  {
    id: 'course-ambassador-module-4',
    courseId: 'course-ambassador',
    title: 'Fundraising Systems',
    description: 'Setting goals and tracking progress.',
    cloudflareVideoId: 'demo-amb-4',
    sortOrder: 4,
    durationSeconds: 740,
  },
  {
    id: 'course-ambassador-module-5',
    courseId: 'course-ambassador',
    title: 'Partnership Care',
    description: 'Following up with supporters.',
    cloudflareVideoId: 'demo-amb-5',
    sortOrder: 5,
    durationSeconds: 690,
  },
  {
    id: 'course-ambassador-module-6',
    courseId: 'course-ambassador',
    title: 'Ambassador Toolkit',
    description: 'Assets, templates, and resources.',
    cloudflareVideoId: 'demo-amb-6',
    sortOrder: 6,
    durationSeconds: 640,
  },
  {
    id: 'course-major-module-1',
    courseId: 'course-major',
    title: '2025 Financial Highlights',
    description: 'Revenue, expenses, and program investment.',
    cloudflareVideoId: 'demo-major-1',
    sortOrder: 1,
    durationSeconds: 700,
  },
  {
    id: 'course-major-module-2',
    courseId: 'course-major',
    title: 'Strategic Initiatives',
    description: 'Priority growth initiatives for 2026.',
    cloudflareVideoId: 'demo-major-2',
    sortOrder: 2,
    durationSeconds: 760,
  },
  {
    id: 'course-major-module-3',
    courseId: 'course-major',
    title: 'Impact Briefing',
    description: 'Deep dive into program outcomes.',
    cloudflareVideoId: 'demo-major-3',
    sortOrder: 3,
    durationSeconds: 680,
  },
];

export const MOCK_PROGRESS: UserCourseProgress[] = [
  {
    id: 'progress-001',
    userId: 'user-001',
    moduleId: 'course-africa-module-1',
    completed: true,
    completedAt: '2026-01-10T12:00:00Z',
    watchTimeSeconds: 920,
  },
  {
    id: 'progress-002',
    userId: 'user-001',
    moduleId: 'course-africa-module-2',
    completed: false,
    watchTimeSeconds: 340,
  },
  {
    id: 'progress-003',
    userId: 'user-006',
    moduleId: 'course-ambassador-module-1',
    completed: true,
    completedAt: '2026-01-21T12:00:00Z',
    watchTimeSeconds: 760,
  },
  {
    id: 'progress-004',
    userId: 'user-006',
    moduleId: 'course-ambassador-module-2',
    completed: false,
    watchTimeSeconds: 220,
  },
  {
    id: 'progress-005',
    userId: 'user-004',
    moduleId: 'course-foundation-module-1',
    completed: true,
    completedAt: '2026-01-20T12:00:00Z',
    watchTimeSeconds: 780,
  },
];

export const MOCK_NOTES: CourseNote[] = [
  {
    id: 'note-001',
    userId: 'user-001',
    moduleId: 'course-africa-module-1',
    content: 'Key takeaway: Favor pairs local leadership with long-term community support.',
    updatedAt: '2026-01-12T09:15:00Z',
  },
];

export const MOCK_USER_ROLES: UserRoleAssignment[] = [
  {
    id: 'role-admin-super',
    userId: 'admin-001',
    roleKey: 'super_admin',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
];

export const MOCK_QUIZ_ATTEMPTS: UserQuizAttempt[] = [
  {
    id: 'attempt-001',
    userId: 'user-006',
    courseId: 'course-ambassador',
    moduleId: 'course-ambassador-module-2',
    attemptNumber: 1,
    scorePercent: 75,
    correctAnswers: 3,
    totalQuestions: 4,
    passed: true,
    answers: {},
    questionOrder: [],
    optionOrder: {},
    startedAt: '2026-01-24T10:00:00Z',
    submittedAt: '2026-01-24T10:06:00Z',
    durationSeconds: 360,
    metadata: { source: 'seed' },
  },
];

export const MOCK_MODULE_EVENTS: CourseModuleEvent[] = [
  {
    id: 'module-event-001',
    userId: 'user-001',
    courseId: 'course-africa',
    moduleId: 'course-africa-module-1',
    eventType: 'module_completed',
    watchTimeSeconds: 920,
    createdAt: '2026-01-10T12:00:00Z',
    metadata: { source: 'seed' },
  },
  {
    id: 'module-event-002',
    userId: 'user-006',
    courseId: 'course-ambassador',
    moduleId: 'course-ambassador-module-1',
    eventType: 'module_completed',
    watchTimeSeconds: 760,
    createdAt: '2026-01-21T12:00:00Z',
    metadata: { source: 'seed' },
  },
];

export const MOCK_COHORTS: CourseCohort[] = [
  {
    id: 'cohort-africa-spring',
    courseId: 'course-africa',
    name: 'Spring 2026 Cohort',
    description: 'Weekly cohort for Africa Programs Overview learners.',
    startsAt: '2026-03-01T00:00:00Z',
    endsAt: '2026-04-30T23:59:59Z',
    isActive: true,
    createdBy: 'admin-001',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
    membersCount: 3,
  },
  {
    id: 'cohort-vision-facilitated',
    courseId: 'course-vision',
    name: 'Facilitated Track A',
    description: 'Instructor-led discussions and weekly reflection prompts.',
    startsAt: '2026-03-10T00:00:00Z',
    endsAt: '2026-05-01T23:59:59Z',
    isActive: true,
    createdBy: 'admin-001',
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
    membersCount: 2,
  },
];

export const MOCK_COHORT_MEMBERS: CourseCohortMember[] = [
  {
    id: 'cohort-member-001',
    cohortId: 'cohort-africa-spring',
    userId: 'user-001',
    membershipRole: 'learner',
    joinedAt: '2026-02-02T12:00:00Z',
  },
  {
    id: 'cohort-member-002',
    cohortId: 'cohort-africa-spring',
    userId: 'user-006',
    membershipRole: 'learner',
    joinedAt: '2026-02-02T13:00:00Z',
  },
  {
    id: 'cohort-member-003',
    cohortId: 'cohort-africa-spring',
    userId: 'admin-001',
    membershipRole: 'instructor',
    joinedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'cohort-member-004',
    cohortId: 'cohort-vision-facilitated',
    userId: 'user-003',
    membershipRole: 'learner',
    joinedAt: '2026-02-06T11:00:00Z',
  },
  {
    id: 'cohort-member-005',
    cohortId: 'cohort-vision-facilitated',
    userId: 'admin-001',
    membershipRole: 'instructor',
    joinedAt: '2026-02-05T10:00:00Z',
  },
];

export const MOCK_DISCUSSION_THREADS: CourseDiscussionThread[] = [
  {
    id: 'thread-africa-001',
    courseId: 'course-africa',
    cohortId: 'cohort-africa-spring',
    moduleId: 'course-africa-module-1',
    authorUserId: 'admin-001',
    authorName: 'Avery Admin',
    title: 'Welcome thread: introduce yourself',
    body: 'Share where you are serving and one thing you hope to learn in this course.',
    pinned: true,
    locked: false,
    replyCount: 2,
    lastActivityAt: '2026-02-08T15:00:00Z',
    createdAt: '2026-02-07T12:00:00Z',
    updatedAt: '2026-02-08T15:00:00Z',
  },
  {
    id: 'thread-africa-002',
    courseId: 'course-africa',
    cohortId: 'cohort-africa-spring',
    moduleId: 'course-africa-module-2',
    authorUserId: 'user-001',
    authorName: 'Emma Carter',
    title: 'Question about module 2 case study',
    body: 'What indicators do we use to evaluate early outcomes in education projects?',
    pinned: false,
    locked: false,
    replyCount: 1,
    lastActivityAt: '2026-02-09T11:00:00Z',
    createdAt: '2026-02-09T10:20:00Z',
    updatedAt: '2026-02-09T11:00:00Z',
  },
];

export const MOCK_DISCUSSION_REPLIES: CourseDiscussionReply[] = [
  {
    id: 'thread-reply-001',
    threadId: 'thread-africa-001',
    authorUserId: 'user-001',
    authorName: 'Emma Carter',
    body: 'I am serving in Atlanta and want to improve how I communicate program impact.',
    isInstructorReply: false,
    createdAt: '2026-02-08T13:00:00Z',
    updatedAt: '2026-02-08T13:00:00Z',
  },
  {
    id: 'thread-reply-002',
    threadId: 'thread-africa-001',
    authorUserId: 'admin-001',
    authorName: 'Avery Admin',
    body: 'Great to have you here. We will cover impact storytelling in module 4.',
    isInstructorReply: true,
    createdAt: '2026-02-08T15:00:00Z',
    updatedAt: '2026-02-08T15:00:00Z',
  },
  {
    id: 'thread-reply-003',
    threadId: 'thread-africa-002',
    authorUserId: 'admin-001',
    authorName: 'Avery Admin',
    body: 'We use attendance consistency, mentor retention, and literacy progression as early indicators.',
    isInstructorReply: true,
    createdAt: '2026-02-09T11:00:00Z',
    updatedAt: '2026-02-09T11:00:00Z',
  },
];

export const MOCK_GRANTS: FoundationGrant[] = [
  {
    id: 'grant-001',
    userId: 'user-004',
    grantName: 'Education Impact Expansion',
    amount: 25000,
    startDate: '2025-07-01',
    endDate: '2026-06-30',
    status: 'active',
    nextReportDue: '2026-03-01',
    notes: 'Quarterly reporting required. Site visit planned for May.',
    createdAt: '2025-06-10T12:00:00Z',
  },
  {
    id: 'grant-002',
    userId: 'user-004',
    grantName: 'Community Health Clinics',
    amount: 18000,
    startDate: '2024-04-01',
    endDate: '2025-03-30',
    status: 'completed',
    nextReportDue: '2025-04-15',
    notes: 'Final report submitted.',
    createdAt: '2024-03-10T12:00:00Z',
  },
];

export const MOCK_PREFERENCES: CommunicationPreferences[] = [
  {
    id: 'pref-001',
    userId: 'user-001',
    emailNewsletterWeekly: true,
    emailNewsletterMonthly: true,
    emailQuarterlyReport: true,
    emailAnnualReport: true,
    emailEvents: true,
    emailPrayer: true,
    emailGivingConfirmations: true,
    smsEnabled: false,
    smsGiftConfirmations: false,
    smsEventReminders: false,
    smsUrgentOnly: false,
    mailEnabled: true,
    mailNewsletterQuarterly: true,
    mailAnnualReport: true,
    mailHolidayCard: true,
    mailAppeals: false,
    blackbaudSolicitCodes: ['EMAIL_ONLY'],
    updatedAt: '2026-01-15T12:00:00Z',
  },
];

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: 'content-001',
    title: 'Q4 2025 Impact Report',
    excerpt: 'A quarterly look at how partners advanced the mission across four countries.',
    body: 'This report summarizes education, health, and discipleship outcomes from Q4 2025.',
    type: 'report',
    accessLevel: 'partner',
    date: '2026-01-18',
    author: 'Favor International',
    tags: ['impact', 'report', 'partner'],
    coverImage: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?q=80&w=1400&auto=format&fit=crop',
    fileUrl: '/mock/impact-report-q4-2025.pdf',
  },
  {
    id: 'content-002',
    title: 'Prayer Focus: Eastern Uganda Schools',
    excerpt: 'Join us in praying for teachers and students as the new term begins.',
    body: 'Specific prayer requests and stories from the field.',
    type: 'prayer',
    accessLevel: 'all',
    date: '2026-01-10',
    author: 'Partner Care',
    tags: ['prayer', 'uganda'],
  },
  {
    id: 'content-003',
    title: 'Foundation Partner Briefing',
    excerpt: 'Board-ready insights on outcomes and financial stewardship.',
    body: 'Metrics, KPIs, and leadership updates tailored for foundations.',
    type: 'report',
    accessLevel: 'foundation',
    date: '2026-01-05',
    author: 'Favor Leadership',
    tags: ['foundation', 'briefing', 'report', 'board'],
    coverImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=1400&auto=format&fit=crop',
    fileUrl: '/mock/foundation-briefing.pdf',
  },
  {
    id: 'content-004',
    title: 'Ambassador Campaign Toolkit',
    excerpt: 'A ready-to-share toolkit with graphics and messaging.',
    body: 'Social media assets, talking points, and a planning checklist.',
    type: 'resource',
    accessLevel: 'ambassador',
    date: '2026-01-22',
    author: 'Ambassador Team',
    tags: ['ambassador', 'resources', 'campaign', 'training'],
    fileUrl: '/mock/ambassador-toolkit.zip',
  },
  {
    id: 'content-005',
    title: 'DAF Giving Checklist',
    excerpt: 'A simple checklist for recommending a grant through your DAF provider.',
    body: 'Step-by-step recommendations and FAQ for DAF donors.',
    type: 'resource',
    accessLevel: 'daf',
    date: '2025-12-20',
    author: 'Giving Team',
    tags: ['daf', 'giving', 'grant'],
  },
  {
    id: 'content-006',
    title: 'Leadership Update: Spring Initiatives',
    excerpt: 'New initiatives launching in 2026 and how to engage.',
    body: 'Highlights on program expansions and new partnerships.',
    type: 'update',
    accessLevel: 'partner',
    date: '2026-01-28',
    author: 'Favor International',
    tags: ['update', 'impact'],
  },
  {
    id: 'content-007',
    title: 'Major Donor Financial Summary',
    excerpt: 'A detailed summary of financial stewardship for major partners.',
    body: 'Program investment and audited financial overview.',
    type: 'report',
    accessLevel: 'major_donor',
    date: '2026-01-02',
    author: 'Finance Team',
    tags: ['finance', 'donor', 'stewardship', 'financial'],
    fileUrl: '/mock/major-donor-summary.pdf',
  },
  {
    id: 'content-008',
    title: 'Volunteer Orientation Pack',
    excerpt: 'Everything you need to get started as a Favor volunteer.',
    body: 'Guidelines, schedule expectations, and onboarding steps.',
    type: 'resource',
    accessLevel: 'volunteer',
    date: '2026-01-14',
    author: 'Volunteer Operations',
    tags: ['volunteer', 'training', 'resource'],
  },
  {
    id: 'content-009',
    title: 'Church Mission Sunday Kit',
    excerpt: 'Slides, bulletin inserts, and a sermon guide for your next mission Sunday.',
    body: 'Downloadable assets and guidance for engaging your congregation.',
    type: 'resource',
    accessLevel: 'church',
    date: '2026-01-26',
    author: 'Church Partner Team',
    tags: ['church', 'mission-sunday', 'materials'],
    coverImage: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=1400&auto=format&fit=crop',
    fileUrl: '/mock/church-mission-sunday-kit.zip',
  },
];

export const MOCK_EVENTS: PortalEvent[] = [
  {
    id: 'event-001',
    title: 'Partner Leadership Summit',
    description: 'Annual gathering for partner leaders and staff.',
    date: '2026-03-15',
    location: 'Nashville, TN',
    audience: 'partner',
  },
  {
    id: 'event-002',
    title: 'Church Partners Conference',
    description: 'A virtual conference for church partners.',
    date: '2026-06-20',
    location: 'Virtual',
    audience: 'church',
  },
  {
    id: 'event-003',
    title: 'Ambassador Training Day',
    description: 'Skill-building day for ambassadors.',
    date: '2026-04-09',
    location: 'Dallas, TX',
    audience: 'ambassador',
  },
  {
    id: 'event-004',
    title: 'Volunteer Welcome Session',
    description: 'Orientation for new volunteers.',
    date: '2026-02-20',
    location: 'Virtual',
    audience: 'volunteer',
  },
];

export const MOCK_TEMPLATES: CommunicationTemplate[] = [
  {
    id: 'template-001',
    channel: 'email',
    name: 'Giving Confirmation',
    subject: 'Thank you for your gift to Favor International',
    content: 'Dear {{firstName}}, your gift of {{amount}} has been received.',
    status: 'active',
    updatedAt: '2026-01-18T12:00:00Z',
  },
  {
    id: 'template-002',
    channel: 'email',
    name: 'Quarterly Impact Report',
    subject: 'Your quarterly impact report is ready',
    content: 'Hello {{firstName}}, download the latest impact report.',
    status: 'active',
    updatedAt: '2026-01-10T12:00:00Z',
  },
  {
    id: 'template-003',
    channel: 'sms',
    name: 'Gift Confirmation SMS',
    content: 'Favor Intl: Your gift of {{amount}} was received. Thank you!',
    status: 'draft',
    updatedAt: '2026-01-05T12:00:00Z',
  },
  {
    id: 'template-004',
    channel: 'direct_mail',
    name: 'Annual Report Mailing',
    content: 'Printed annual report mailing for partners who opted in.',
    status: 'active',
    updatedAt: '2025-12-15T12:00:00Z',
  },
];

export const MOCK_ACTIVITY: ActivityEvent[] = [
  {
    id: 'activity-001',
    type: 'gift_created',
    userId: 'user-001',
    createdAt: '2026-01-12T14:30:00Z',
    metadata: { amount: 100, designation: 'Clean Water Initiative' },
  },
  {
    id: 'activity-002',
    type: 'course_completed',
    userId: 'user-006',
    createdAt: '2026-01-21T11:10:00Z',
    metadata: { courseId: 'course-ambassador', module: 'Ambassador DNA' },
  },
  {
    id: 'activity-003',
    type: 'content_viewed',
    userId: 'user-004',
    createdAt: '2026-01-18T09:05:00Z',
    metadata: { contentId: 'content-003' },
  },
  {
    id: 'activity-004',
    type: 'support_ticket',
    userId: 'user-003',
    createdAt: '2026-01-28T16:40:00Z',
    metadata: { subject: 'Material order request' },
  },
];
